### ISSUE TITLE
send/recv timeout 설정 없음.

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#14]
- [x] send/recv_time_out config parse
- [x] 구현하기

**Comment by jinbekim** [comment]
어떻게 해야할지 모르겠어서 안 건들였습니다. 공부할게요 ㅜ

**Comment by evelon** [comment]
setsockopt(sClient, SOL_SOCKET, SO_RCVTIMEO, (char *)&recvTimeout ,sizeof(int));
setsockopt(sClient, SOL_SOCKET, SO_SNDTIMEO, (char *)&sendTimeout ,sizeof(int));
이걸로 해결되었습니다.
