### ISSUE TITLE
400번 대 오류가 들어왔을 때 어디서 처리하느냐

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#25]
Host 헤더가 없을 경우 해당하는 서버가 없는데 에러를 보내야하는 문제가 생김. PortManager에서 처리하거나 default_server에서 처리해야함.
어느 경우에도 Client가 해당 에러를 Request에 적어서 보내줘야합니다.

**Comment by jinbekim** [comment]
넹

**Comment by jinbekim** [comment]
이거는 리소스의 상태(status)에 해당 에러(int)를 표기하는 식으로 일단 해놨는데 계속 고민해 보죠.

**Comment by jinbekim** [comment]
request의 상태를 바꾸는 식으로 함.?

**Comment by jinbekim** [comment]
server에 req의 상택값으로 전해줘 server 안에서 처리 전에 조건문으로 에러페이지를 생성함
