### ISSUE TITLE
저희 Client랑 ServerManager 이름이...

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#34]
이상해지지 않았어요?

**Comment by evelon** [comment]
Client가 현재 기능이 두 개인 것 같습니다.
1. Re3 deque의 입출력과 순서 조작
2. Request parse

**Comment by evelon** [comment]
ServerManager은 seyu님이 EventHandler가 나을 것 같다고 하셨습니다.

**Comment by jinbekim** [comment]
서버매니저는 저희가 만든게 웹서버니까 서버매니저는 괜찮은거같아요.
서버매니저가 전체 총괄하고 있으니까.
근데 클라이언트는 .. 조금 애매하네요
