### ISSUE TITLE
resource가 매우 클 경우(예를들어 큰 규모의 cgi인 경우) chunked로 대응하기. 그에 따라 sendRsp 주체 결정

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#37]
buffer size 이하일 경우 content-length 방식으로 보내기.
buffer size 이상인 경우 헤더는 chunked 방식으로 보내고, 그 다음 resource를 ServerManager에서 chunked 방식으로 보내기.

**Comment by evelon** [comment]
or 전부 chunked 방식으로 보내기

**Comment by jinbekim** [comment]
sendResponse를 어디서 할것인가?

1. client sendResponse 메소드에서
2. serverManager에서 chunked면 SM에서 chunked 형식에 맞게 보내줘야 할듯. length면 그냥 보내면 되겠지만.
3. 그에따른 헤더의 경우에는 리소스 특징(fstat??) 구한다음에 size(buffer를 기준으로 무슨버퍼?)에 따라 SM이 Server에 신호를 준다(?)

**Comment by jinbekim** [comment]
전부다 chunked로 대응하는게 좋아보여요
