### ISSUE TITLE
enum type 이름

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#38]
https://google.github.io/styleguide/cppguide.html#Enumerator_Names
죄송합니다

```
enum MyEnumType {
    kFirstEnum,
    kSecondEnum
}
```
형식으로 적는게 맞다고 합니다. 타입 이름 규칙을 멤버 이름 규칙으로 잘못 알고 있었네요.

**Comment by jinbekim** [comment]
앞에 k는 아무 의미 없는 거죠?
