### ISSUE TITLE
혹시 Header를 여러 개 받는 기능이 있나요?

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#39]
혹시 Header를 여러 개 받는 기능이 있나요?

```
Cache-Control: no-cache, no-store

is equivalent to (order is important)

Cache-Control: no-cache
Cache-Control: no-store
```
라고 합니다.
https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable

_Originally posted by @evelon in https://github.com/socketsocket/passive_team/pull/30#discussion_r682522280_

**Comment by jinbekim** [comment]
따로 구현한 적은 없는데요.
`
int	Request::insertHeader(std::string& key, std::string& value) {
	this->header.insert(std::make_pair(key, value));
}
` 이런식으로 구현해서 아마 안들어갈꺼에요. 근데 이게 헤더마다 중복된 값을 인정하는 것도 있을것 같도 무시하는 것도 있을것 같은게..
심상치 않을것 같은데요?

**Comment by jinbekim** [comment]
일단 request로 들어오는 헤더는 같은 키라면 밸류에 붙여서 파싱하고 reponse에서 쓸때 맨앞에꺼만 사용하든 맨 뒤에꺼만 사용하든 모든 값을 다 쓰든 알아서 한다.로 구현??
