### ISSUE TITLE
에바롭게 고안해보아야합니다.

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#41]
그럴수있다면 그런방향으로 거치는게 최대한좋을거같긴한데 에바롭게 고안해보아야합니다.

_Originally posted by @seohee-choi in https://github.com/socketsocket/passive_team/pull/30#discussion_r682480908_

**Comment by seohee-choi** [comment]
![image](https://user-images.githubusercontent.com/60740882/128471422-9a78cbb2-6282-46e1-b2f1-7a6eb9faf815.png)
