### ISSUE TITLE
Client::passResource가 잘못되어있습니다.

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#44]
여기서 deque이 모두 pop되어버리는 경우 recvRequest에서 back() 참조시 segfault가 뜨게 됩니다. recvRequest를 수정하는게 좋다고 생각합니다.

**Comment by jinbekim** [comment]
client에 passResource가 없어요.... 어디 말씀하시는 건가요?

**Comment by jinbekim** [comment]
생성자에서 deque 초기화하는 부분을 빼고 recvRequest에 다음과 같은 코드를 삽입했습니다.

```
	if (this->re3_deque.empty()) {
		this->re3_deque.push_back(Re3(client_fd));
		this->re3_deque.back().setReqPtr(new Request);
	}
```

**Comment by jinbekim** [comment]
Execution에 푸시했씁니다.

**Comment by evelon** [comment]
감사합니다
