### ISSUE TITLE
파일 확장자가 제대로 처리되지 않습니다.

### ISSUE THREAD

**Issue by evelon** [socketsocket/passive_team#47]
넹~

**Comment by evelon** [comment]
getExtension 함수(인가)를 쓰는 곳에 들어오는게 파일명을 제외한 경로명인 것 같습니다.

**Comment by seohee-choi** [comment]
발생 버그: .html 확장자 인식이 안되어서 텍스트파일로 보내지는 현상
버그 발생 조건: root 접속시 
원인:
root로 접속시, indexfile이 존재하는 경우
fileExtension 함수에 들어오는 resource_path가 index파일명까지 붙인 경로가 아니라 root경로 그대로여서 index파일의 확장자를 찾지 못하고, .html이 아닌 text로 판별하기 때문

**Comment by seohee-choi** [comment]
해결방법 : Resource 객체가 본인의 uri(파일의 경로)를 백업해두는 변수를 갖게하여 index파일 경로를 백업할 수 있게 함.
