### ISSUE TITLE
적절한 GET 요청이 부적절한 오류

### ISSUE THREAD

**Issue by seohee-choi** [socketsocket/passive_team#48]
> 적절한 곳에 루트를 설정해두고 거기에다 적절한 파일을 두고 그 파일을 GET하는 http 요청을 보내면 요상한 오류가 나는데 그 오류를 보세요
> 이상한 곳에서 할당이랑 할당해제가 되고 이상한 곳에서 그걸 호출해서 쓴다고 해요
By @evelon

**Comment by jinbekim** [comment]
오류조차 못 내겠어요..

**Comment by seohee-choi** [comment]
jolim님:어디선가 Location을 할당해제하는 것 같아요.

http://localhost:8080/index.html로 접속해서 여러번 새로고침하면 세그폴트가 뜨긴 하네요
