### ISSUE TITLE
Fix: Server.cpp:10, request의 status가 꼭 kFinished가 아닐 수 있음.

### ISSUE THREAD

**Issue by jinbekim** [socketsocket/passive_team#51]
request에 length정보가 없을 경우 kLengthReq 상태로 반환되는데,
이 경우 client와 연결을 끊기로 함.
만약 kFinished만 체크할 경우 무한루프에 빠짐 client::recvRequest <-> server::makeResponse;

**Comment by seohee-choi** [comment]
제가 고칠까용??

**Comment by jinbekim** [comment]
아 네 그렇게 해주세요

**Comment by jinbekim** [comment]
ServerManager측에서 연결 끊는거랑, client측 처리는 제가 해볼게요.
