### ISSUE TITLE
CGI 설계 및 구현 

### ISSUE THREAD

**Issue by seohee-choi** [socketsocket/passive_team#55]
### 해야할일
1. 환경변수 만드는 함수
2. fork및 실행부
3. fd_set

---

1. cgi인지 확인하고, 실행 파일에 필요한 변수들을(meta variable) 스트링 env_var들로 만들어주는 함수
	인자로 들어갈 파일의 유효성을 검사하고 cgi인지 확인
2. 저장된 meta variable들을 envp 형태로 만드는 함수
	@return 만들어진 envp 포인터
3. cgi 프로그램을 실행한다음 client Fd를 fd_set해 실행결과를 write하는 함수
	fork()를 이용해 프로세스를 나눈 후 자식 프로세스에서 execve()를 통해 실행시켜 줌
	@param int clientFd : 쓸 client fd

**Comment by jinbekim** [comment]
cgiConnector 클래스를 생성하여, (정적으로 만들어도 될듯)
리소스 상태에 맞는 함수를 호출하여 실행.
이에 부산되는 데이터 (pid, fd)들은 resource객체에 저장됨.
완료. close #55
