### ISSUE TITLE
POST 요청시 411이 뜨고, 그 이후로는 GET/POST 요청이 모두 405 처리되는 문제

### ISSUE THREAD

**Issue by seohee-choi** [socketsocket/passive_team#56]
0. get만하면 문제 없음.
1. 맨 처음 post 요청 보내면 411응답이 뜸
2. 그 후로는 get/post 요청을 해도 계속해서 405응답만 발생

**Comment by jinbekim** [comment]
제가 실행하면  에러페이지는 안뜨는데 
![image](https://user-images.githubusercontent.com/59330110/131300844-4dda7716-b405-470f-9707-5f88ab0e2a28.png)
이런 fd가 죽지않고 살아있음, 클라이언트랑 연결이 안끊어 지는 것 같은데 확인해 봐야할듯.

**Comment by jinbekim** [comment]
서버 종료시켜보니 그때야 응답이 오는데 이것도 delete랑 똑같은 이유일듯 하네요.
서버가 종료되야 응답도 보내지네요.

**Comment by jinbekim** [comment]
#61 이랑 같은 이유 일듯함.
